export type Review = { source: string; text: string; url: string };

export interface AiTool {
  name: string;
  description: string;
  site: string;
  positives: Review[];
  negatives: Review[];
}

export type CategoryKey =
  | "free"
  | "paid"
  | "developer"
  | "content"
  | "media"
  | "cyber"
  | "data"
  | "design"
  | "marketing"
  | "automation";

export interface Category {
  key: CategoryKey;
  label: string;
  emoji: string;
  blurb: string;
  /** Distinct theme color used for glow effects (CSS color string). */
  glow: string;
  tools: AiTool[];
}

const r = (source: string, text: string, url: string): Review => ({ source, text, url });

export const CATEGORIES: Category[] = [
  {
    key: "free",
    label: "Completely Free",
    emoji: "🎁",
    blurb: "Powerful AI you can use without paying a cent.",
    glow: "rgba(52, 211, 153, 0.65)",
    tools: [
      {
        name: "Gemini Free",
        description: "Google's free multimodal AI assistant.",
        site: "https://gemini.google.com/",
        positives: [r("G2", "Fast, accurate, tight Google integration.", "https://www.g2.com/products/google-gemini/reviews"), r("Product Hunt", "Great free multimodal capabilities.", "https://www.producthunt.com/products/google-gemini")],
        negatives: [r("Reddit", "Occasionally refuses reasonable prompts.", "https://www.reddit.com/r/Bard/"), r("G2", "Depth varies vs. paid models.", "https://www.g2.com/products/google-gemini/reviews")],
      },
      {
        name: "Hugging Face Chat",
        description: "Open-source chat with many free models.",
        site: "https://huggingface.co/chat",
        positives: [r("Reddit", "Amazing that so many open models are free.", "https://www.reddit.com/r/LocalLLaMA/"), r("Product Hunt", "Great for experimenting.", "https://www.producthunt.com/products/huggingface")],
        negatives: [r("Reddit", "UI is bare vs. ChatGPT.", "https://www.reddit.com/r/LocalLLaMA/"), r("G2", "Quality depends on model choice.", "https://www.g2.com/products/hugging-face/reviews")],
      },
      {
        name: "NotebookLM",
        description: "Google's source-grounded research notebook.",
        site: "https://notebooklm.google.com/",
        positives: [r("Product Hunt", "Audio overviews are magical.", "https://www.producthunt.com/products/notebooklm"), r("Reddit", "Best RAG-style tool that's actually free.", "https://www.reddit.com/r/NotebookLM/")],
        negatives: [r("Reddit", "Source limits per notebook.", "https://www.reddit.com/r/NotebookLM/"), r("G2", "No true real-time collaboration yet.", "https://www.g2.com/products/notebooklm/reviews")],
      },
      {
        name: "Jan AI",
        description: "Open-source offline ChatGPT alternative.",
        site: "https://jan.ai/",
        positives: [r("GitHub", "Runs LLMs fully offline, privacy-first.", "https://github.com/janhq/jan"), r("Product Hunt", "Beautiful desktop UI for local models.", "https://www.producthunt.com/products/jan")],
        negatives: [r("Reddit", "Heavy on RAM with bigger models.", "https://www.reddit.com/r/LocalLLaMA/"), r("GitHub", "Some extensions still unstable.", "https://github.com/janhq/jan/issues")],
      },
      {
        name: "DuckDuckGo Chat",
        description: "Anonymous chat with multiple free models.",
        site: "https://duck.ai/",
        positives: [r("Reddit", "Truly private and free access to GPT/Claude.", "https://www.reddit.com/r/duckduckgo/"), r("Product Hunt", "Zero login, zero tracking.", "https://www.producthunt.com/products/duckduckgo-ai-chat")],
        negatives: [r("Reddit", "No memory between sessions.", "https://www.reddit.com/r/duckduckgo/"), r("G2", "Limited to shorter contexts.", "https://www.g2.com/products/duckduckgo/reviews")],
      },
      {
        name: "Phind Free",
        description: "AI search engine tuned for developers.",
        site: "https://www.phind.com/",
        positives: [r("Reddit", "Cites sources better than ChatGPT.", "https://www.reddit.com/r/webdev/"), r("Product Hunt", "Great free dev-focused answers.", "https://www.producthunt.com/products/phind")],
        negatives: [r("Reddit", "Pro tier pushes the best model.", "https://www.reddit.com/r/webdev/"), r("G2", "Occasional stale search results.", "https://www.g2.com/products/phind/reviews")],
      },
      {
        name: "DeepL Write",
        description: "AI writing polish and rewrites for free.",
        site: "https://www.deepl.com/write",
        positives: [r("G2", "Best rewrites in EU languages.", "https://www.g2.com/products/deepl/reviews"), r("Trustpilot", "Very natural tone tweaks.", "https://www.trustpilot.com/review/deepl.com")],
        negatives: [r("Reddit", "Free tier char cap is low.", "https://www.reddit.com/r/languagelearning/"), r("G2", "No long-form generation.", "https://www.g2.com/products/deepl/reviews")],
      },
      {
        name: "Llamafile",
        description: "Single-file distributable local LLM runner.",
        site: "https://github.com/Mozilla-Ocho/llamafile",
        positives: [r("GitHub", "Truly zero-setup local LLMs.", "https://github.com/Mozilla-Ocho/llamafile"), r("Hacker News", "Genius single-binary distribution.", "https://news.ycombinator.com/item?id=38464057")],
        negatives: [r("Reddit", "CLI-heavy for newcomers.", "https://www.reddit.com/r/LocalLLaMA/"), r("GitHub", "Windows performance trails Linux.", "https://github.com/Mozilla-Ocho/llamafile/issues")],
      },
      {
        name: "Ollama",
        description: "Run open LLMs locally with one command.",
        site: "https://ollama.com/",
        positives: [r("GitHub", "Simplest way to run Llama/Mistral locally.", "https://github.com/ollama/ollama"), r("Reddit", "Amazing devx for local AI.", "https://www.reddit.com/r/LocalLLaMA/")],
        negatives: [r("Reddit", "GPU offload can be tricky.", "https://www.reddit.com/r/LocalLLaMA/"), r("GitHub", "Model catalog updates lag upstream.", "https://github.com/ollama/ollama/issues")],
      },
      {
        name: "Claude Free Tier",
        description: "Anthropic's Claude with a generous free tier.",
        site: "https://claude.ai/",
        positives: [r("G2", "Best free writing partner.", "https://www.g2.com/products/claude/reviews"), r("Reddit", "Free tier still very capable.", "https://www.reddit.com/r/ClaudeAI/")],
        negatives: [r("Reddit", "Message caps hit fast.", "https://www.reddit.com/r/ClaudeAI/"), r("G2", "Refuses some benign tasks.", "https://www.g2.com/products/claude/reviews")],
      },
    ],
  },
  {
    key: "paid",
    label: "Paid & Enterprise",
    emoji: "💳",
    blurb: "Premium platforms with subscription pricing.",
    glow: "rgba(251, 191, 36, 0.65)",
    tools: [
      {
        name: "ChatGPT Plus",
        description: "OpenAI's flagship chatbot with advanced tools.",
        site: "https://chat.openai.com/",
        positives: [r("Trustpilot", "Best all-around assistant for work.", "https://www.trustpilot.com/review/openai.com"), r("G2", "Voice + vision are game changers.", "https://www.g2.com/products/chatgpt/reviews")],
        negatives: [r("Reddit", "Message caps feel restrictive.", "https://www.reddit.com/r/ChatGPTPro/"), r("Trustpilot", "Occasional downtime at peak.", "https://www.trustpilot.com/review/openai.com")],
      },
      {
        name: "Claude Pro",
        description: "Anthropic's long-context reasoning assistant.",
        site: "https://claude.ai/",
        positives: [r("G2", "Best writing partner for long-form docs.", "https://www.g2.com/products/claude/reviews"), r("Reddit", "Great at nuanced instructions.", "https://www.reddit.com/r/ClaudeAI/")],
        negatives: [r("Reddit", "Usage limits kick in fast.", "https://www.reddit.com/r/ClaudeAI/"), r("G2", "Refuses tasks other AIs handle.", "https://www.g2.com/products/claude/reviews")],
      },
      {
        name: "Perplexity Pro",
        description: "AI answer engine with cited sources.",
        site: "https://www.perplexity.ai/",
        positives: [r("Product Hunt", "Best cited search on the market.", "https://www.producthunt.com/products/perplexity-ai"), r("G2", "Focus modes are super useful.", "https://www.g2.com/products/perplexity-ai/reviews")],
        negatives: [r("Reddit", "Sometimes summarizes over-broadly.", "https://www.reddit.com/r/perplexity_ai/"), r("Trustpilot", "Pro price bumped recently.", "https://www.trustpilot.com/review/perplexity.ai")],
      },
      {
        name: "Gemini Advanced",
        description: "Google's premium Gemini with 1M-token context.",
        site: "https://gemini.google.com/advanced",
        positives: [r("G2", "Deep Google Workspace integration.", "https://www.g2.com/products/google-gemini/reviews"), r("Product Hunt", "Huge context helps with docs.", "https://www.producthunt.com/products/google-gemini")],
        negatives: [r("Reddit", "Still trails GPT-5 in reasoning.", "https://www.reddit.com/r/Bard/"), r("G2", "Bundled with pricey One AI plan.", "https://www.g2.com/products/google-gemini/reviews")],
      },
      {
        name: "Glean",
        description: "Enterprise AI work assistant with unified search.",
        site: "https://www.glean.com/",
        positives: [r("G2", "Finally search that works across our tools.", "https://www.g2.com/products/glean/reviews"), r("Gartner Peer Insights", "Best enterprise RAG we've deployed.", "https://www.gartner.com/reviews/market/insight-engines")],
        negatives: [r("G2", "Setup + connectors take time.", "https://www.g2.com/products/glean/reviews"), r("Gartner Peer Insights", "Pricing scales quickly.", "https://www.gartner.com/reviews/market/insight-engines")],
      },
      {
        name: "Kapa.ai",
        description: "AI answer bot trained on your docs/community.",
        site: "https://www.kapa.ai/",
        positives: [r("Product Hunt", "Cut our support ticket load in half.", "https://www.producthunt.com/products/kapa-ai"), r("G2", "Great citations to docs.", "https://www.g2.com/products/kapa-ai/reviews")],
        negatives: [r("G2", "Needs clean docs to shine.", "https://www.g2.com/products/kapa-ai/reviews"), r("Product Hunt", "Custom styling is limited.", "https://www.producthunt.com/products/kapa-ai")],
      },
      {
        name: "Granica",
        description: "Data privacy layer for enterprise AI.",
        site: "https://granica.ai/",
        positives: [r("Product Hunt", "Slashes token costs on large datasets.", "https://www.producthunt.com/products/granica"), r("Gartner Peer Insights", "Solid PII masking for AI pipelines.", "https://www.gartner.com/reviews/market/data-security")],
        negatives: [r("G2", "Very enterprise-focused pricing.", "https://www.g2.com/products/granica/reviews"), r("Gartner Peer Insights", "Onboarding requires infra work.", "https://www.gartner.com/reviews/market/data-security")],
      },
      {
        name: "Heptabase",
        description: "Visual knowledge base with AI copilots.",
        site: "https://heptabase.com/",
        positives: [r("Product Hunt", "Best whiteboard-thinking app I've used.", "https://www.producthunt.com/products/heptabase"), r("Reddit", "AI card summaries are gold.", "https://www.reddit.com/r/Heptabase/")],
        negatives: [r("Reddit", "Learning curve is real.", "https://www.reddit.com/r/Heptabase/"), r("Product Hunt", "Pricing is on the high side.", "https://www.producthunt.com/products/heptabase")],
      },
      {
        name: "Feedly Leo",
        description: "AI research assistant built into Feedly.",
        site: "https://feedly.com/ai",
        positives: [r("G2", "Cuts noise across hundreds of feeds.", "https://www.g2.com/products/feedly/reviews"), r("Product Hunt", "Threat intel workflows are top-tier.", "https://www.producthunt.com/products/feedly")],
        negatives: [r("G2", "AI is behind Enterprise paywall.", "https://www.g2.com/products/feedly/reviews"), r("Trustpilot", "Setup of Leo skills is fiddly.", "https://www.trustpilot.com/review/feedly.com")],
      },
      {
        name: "Writer Enterprise",
        description: "Enterprise generative AI writing platform.",
        site: "https://writer.com/",
        positives: [r("G2", "Brand voice control is unmatched.", "https://www.g2.com/products/writer/reviews"), r("Gartner Peer Insights", "Great compliance + governance controls.", "https://www.gartner.com/reviews/market/generative-ai-platforms")],
        negatives: [r("G2", "Priced for large orgs only.", "https://www.g2.com/products/writer/reviews"), r("Gartner Peer Insights", "Model customization is limited.", "https://www.gartner.com/reviews/market/generative-ai-platforms")],
      },
    ],
  },
  {
    key: "developer",
    label: "Developer Tools & IDE Layers",
    emoji: "🛠️",
    blurb: "AI copilots that live in your editor.",
    glow: "rgba(96, 165, 250, 0.65)",
    tools: [
      {
        name: "GitHub Copilot",
        description: "In-editor completions and chat from GitHub + OpenAI.",
        site: "https://github.com/features/copilot",
        positives: [r("G2", "Massive productivity boost.", "https://www.g2.com/products/github-copilot/reviews"), r("Reddit", "Chat inside VS Code is handy.", "https://www.reddit.com/r/github/")],
        negatives: [r("G2", "Sometimes suggests deprecated APIs.", "https://www.g2.com/products/github-copilot/reviews"), r("Trustpilot", "Enterprise pricing adds up.", "https://www.trustpilot.com/review/github.com")],
      },
      {
        name: "Cursor",
        description: "AI-first code editor built on VS Code.",
        site: "https://cursor.sh/",
        positives: [r("Product Hunt", "Composer edits multi-file like magic.", "https://www.producthunt.com/products/cursor"), r("Reddit", "Fastest prototyping I've done.", "https://www.reddit.com/r/cursor/")],
        negatives: [r("Reddit", "Premium models get expensive.", "https://www.reddit.com/r/cursor/"), r("Product Hunt", "Lag on giant projects.", "https://www.producthunt.com/products/cursor")],
      },
      {
        name: "Codeium",
        description: "Free AI autocomplete and chat for devs.",
        site: "https://codeium.com/",
        positives: [r("G2", "Impressive free alternative to Copilot.", "https://www.g2.com/products/codeium/reviews"), r("Product Hunt", "Works across dozens of editors.", "https://www.producthunt.com/products/codeium")],
        negatives: [r("Reddit", "Trails Copilot slightly on quality.", "https://www.reddit.com/r/Codeium/"), r("G2", "Enterprise onboarding is clunky.", "https://www.g2.com/products/codeium/reviews")],
      },
      {
        name: "Lovable",
        description: "AI app builder that ships full-stack apps.",
        site: "https://lovable.dev/",
        positives: [r("Product Hunt", "Turns a prompt into a real app fast.", "https://www.producthunt.com/products/lovable"), r("Twitter", "Best AI SaaS builder I've tried.", "https://twitter.com/search?q=lovable.dev")],
        negatives: [r("Reddit", "Credits burn on big changes.", "https://www.reddit.com/r/lovable/"), r("Product Hunt", "Some patterns require guidance.", "https://www.producthunt.com/products/lovable")],
      },
      {
        name: "Tabnine",
        description: "Private AI code assistant for teams.",
        site: "https://www.tabnine.com/",
        positives: [r("G2", "Best for privacy-conscious teams.", "https://www.g2.com/products/tabnine/reviews"), r("Product Hunt", "Local models keep code in-house.", "https://www.producthunt.com/products/tabnine")],
        negatives: [r("G2", "Completions less punchy than Copilot.", "https://www.g2.com/products/tabnine/reviews"), r("Reddit", "Chat is a newer add-on.", "https://www.reddit.com/r/programming/")],
      },
      {
        name: "Amazon Q",
        description: "AWS's AI assistant for devs and analysts.",
        site: "https://aws.amazon.com/q/",
        positives: [r("G2", "AWS-aware answers save real time.", "https://www.g2.com/products/amazon-q/reviews"), r("Gartner Peer Insights", "Great for cloud ops teams.", "https://www.gartner.com/reviews/market/generative-ai-platforms")],
        negatives: [r("Reddit", "Best inside AWS console only.", "https://www.reddit.com/r/aws/"), r("G2", "Setup can be permissions-heavy.", "https://www.g2.com/products/amazon-q/reviews")],
      },
      {
        name: "Replit Agent",
        description: "Autonomous coding agent inside Replit.",
        site: "https://replit.com/",
        positives: [r("Product Hunt", "Builds full apps from a prompt.", "https://www.producthunt.com/products/replit"), r("Reddit", "Deploys are one click.", "https://www.reddit.com/r/replit/")],
        negatives: [r("Reddit", "Agent can loop on tricky bugs.", "https://www.reddit.com/r/replit/"), r("Trustpilot", "Compute credits run out fast.", "https://www.trustpilot.com/review/replit.com")],
      },
      {
        name: "Sourcegraph Cody",
        description: "Enterprise code AI with codebase context.",
        site: "https://sourcegraph.com/cody",
        positives: [r("G2", "Best at large codebase awareness.", "https://www.g2.com/products/sourcegraph/reviews"), r("Product Hunt", "Great multi-repo chat.", "https://www.producthunt.com/products/cody")],
        negatives: [r("Reddit", "Latency higher on huge repos.", "https://www.reddit.com/r/programming/"), r("G2", "Pricing skews enterprise.", "https://www.g2.com/products/sourcegraph/reviews")],
      },
      {
        name: "Blackbox AI",
        description: "Code AI with autocomplete and chat.",
        site: "https://www.blackbox.ai/",
        positives: [r("Product Hunt", "Fast completions in any editor.", "https://www.producthunt.com/products/blackbox"), r("G2", "Handy code-from-screenshot feature.", "https://www.g2.com/products/blackbox-ai/reviews")],
        negatives: [r("Reddit", "Answers vary in quality.", "https://www.reddit.com/r/programming/"), r("G2", "UI feels cluttered.", "https://www.g2.com/products/blackbox-ai/reviews")],
      },
      {
        name: "Continue.dev",
        description: "Open-source AI code assistant for any editor.",
        site: "https://continue.dev/",
        positives: [r("GitHub", "Best OSS Copilot alternative.", "https://github.com/continuedev/continue"), r("Reddit", "Bring-your-own-model rocks.", "https://www.reddit.com/r/vscode/")],
        negatives: [r("GitHub", "Config takes tinkering.", "https://github.com/continuedev/continue/issues"), r("Reddit", "Occasional VS Code hiccups.", "https://www.reddit.com/r/vscode/")],
      },
    ],
  },
  {
    key: "content",
    label: "Copywriting & Productivity",
    emoji: "✍️",
    blurb: "Copy, marketing, and writing workflows.",
    glow: "rgba(244, 114, 182, 0.65)",
    tools: [
      {
        name: "Jasper",
        description: "Marketing AI for teams — blogs, ads, brand voice.",
        site: "https://www.jasper.ai/",
        positives: [r("G2", "Brand Voice keeps copy on-brand.", "https://www.g2.com/products/jasper/reviews"), r("Trustpilot", "Templates save hours.", "https://www.trustpilot.com/review/jasper.ai")],
        negatives: [r("G2", "Pricey vs. raw ChatGPT.", "https://www.g2.com/products/jasper/reviews"), r("Trustpilot", "Outputs can feel generic.", "https://www.trustpilot.com/review/jasper.ai")],
      },
      {
        name: "Copy.ai",
        description: "AI copy platform for sales & marketing teams.",
        site: "https://www.copy.ai/",
        positives: [r("G2", "Quick outbound email drafts.", "https://www.g2.com/products/copy-ai/reviews"), r("Trustpilot", "Workflows automate grunt work.", "https://www.trustpilot.com/review/copy.ai")],
        negatives: [r("G2", "Output quality varies.", "https://www.g2.com/products/copy-ai/reviews"), r("Trustpilot", "Support can be slow.", "https://www.trustpilot.com/review/copy.ai")],
      },
      {
        name: "Anyword",
        description: "Predictive copy scoring for marketers.",
        site: "https://anyword.com/",
        positives: [r("G2", "Predictive score actually helps A/B.", "https://www.g2.com/products/anyword/reviews"), r("Product Hunt", "Great for ad variants.", "https://www.producthunt.com/products/anyword")],
        negatives: [r("G2", "Best features are top-tier only.", "https://www.g2.com/products/anyword/reviews"), r("Reddit", "Scoring is a blackbox.", "https://www.reddit.com/r/marketing/")],
      },
      {
        name: "Writesonic",
        description: "AI writing + SEO content platform.",
        site: "https://writesonic.com/",
        positives: [r("G2", "All-in-one writing suite.", "https://www.g2.com/products/writesonic/reviews"), r("Trustpilot", "Chatsonic + article writer combo.", "https://www.trustpilot.com/review/writesonic.com")],
        negatives: [r("Trustpilot", "Word credits eaten fast.", "https://www.trustpilot.com/review/writesonic.com"), r("G2", "Outputs often need heavy editing.", "https://www.g2.com/products/writesonic/reviews")],
      },
      {
        name: "Sudowrite",
        description: "AI writing partner for novelists.",
        site: "https://www.sudowrite.com/",
        positives: [r("Product Hunt", "Best AI for fiction, hands down.", "https://www.producthunt.com/products/sudowrite"), r("Reddit", "Story Engine is inspiring.", "https://www.reddit.com/r/writing/")],
        negatives: [r("Reddit", "Credits burn fast on long books.", "https://www.reddit.com/r/writing/"), r("Trustpilot", "Style drifts in long chapters.", "https://www.trustpilot.com/review/sudowrite.com")],
      },
      {
        name: "Lex Page",
        description: "AI-first writing editor for drafts.",
        site: "https://lex.page/",
        positives: [r("Product Hunt", "Buttery smooth writing UX.", "https://www.producthunt.com/products/lex"), r("Twitter", "Best AI Google-Docs replacement.", "https://twitter.com/search?q=lex.page")],
        negatives: [r("Reddit", "Missing team collab features.", "https://www.reddit.com/r/writing/"), r("Product Hunt", "Free tier is limited.", "https://www.producthunt.com/products/lex")],
      },
      {
        name: "Grammarly Plus",
        description: "AI writing assistant beyond grammar.",
        site: "https://www.grammarly.com/plus",
        positives: [r("G2", "Rewrites are genuinely helpful now.", "https://www.g2.com/products/grammarly/reviews"), r("Trustpilot", "Everywhere I type.", "https://www.trustpilot.com/review/grammarly.com")],
        negatives: [r("G2", "Suggestions can be too formal.", "https://www.g2.com/products/grammarly/reviews"), r("Trustpilot", "Occasional false positives.", "https://www.trustpilot.com/review/grammarly.com")],
      },
      {
        name: "QuillBot",
        description: "AI paraphraser, summarizer, and grammar tool.",
        site: "https://quillbot.com/",
        positives: [r("G2", "Best paraphraser I've used.", "https://www.g2.com/products/quillbot/reviews"), r("Trustpilot", "Great for study workflows.", "https://www.trustpilot.com/review/quillbot.com")],
        negatives: [r("Trustpilot", "Premium prompts get spammy.", "https://www.trustpilot.com/review/quillbot.com"), r("G2", "Ads on free tier.", "https://www.g2.com/products/quillbot/reviews")],
      },
      {
        name: "Rytr",
        description: "Affordable AI writing assistant.",
        site: "https://rytr.me/",
        positives: [r("G2", "Great value for solo creators.", "https://www.g2.com/products/rytr/reviews"), r("Trustpilot", "Simple UI, decent quality.", "https://www.trustpilot.com/review/rytr.me")],
        negatives: [r("G2", "Not enterprise-grade.", "https://www.g2.com/products/rytr/reviews"), r("Trustpilot", "Templates feel dated.", "https://www.trustpilot.com/review/rytr.me")],
      },
      {
        name: "Type Studio",
        description: "AI writing studio for creators and marketers.",
        site: "https://type.ai/",
        positives: [r("Product Hunt", "Clean UI for drafting long-form.", "https://www.producthunt.com/products/type-ai"), r("Twitter", "Great brand voice presets.", "https://twitter.com/search?q=type.ai")],
        negatives: [r("Reddit", "Newer, fewer integrations.", "https://www.reddit.com/r/marketing/"), r("Product Hunt", "Pricing ramp is steep.", "https://www.producthunt.com/products/type-ai")],
      },
    ],
  },
  {
    key: "media",
    label: "Image, Audio & Video Generation",
    emoji: "🎨",
    blurb: "Generative media across image, audio, video.",
    glow: "rgba(168, 85, 247, 0.7)",
    tools: [
      {
        name: "Midjourney",
        description: "Industry-leading AI image generator.",
        site: "https://www.midjourney.com/",
        positives: [r("Reddit", "Stunning artistic quality.", "https://www.reddit.com/r/midjourney/"), r("Product Hunt", "V6 handles text + hands well.", "https://www.producthunt.com/products/midjourney")],
        negatives: [r("Trustpilot", "Discord workflow confusing.", "https://www.trustpilot.com/review/midjourney.com"), r("Reddit", "No free tier anymore.", "https://www.reddit.com/r/midjourney/")],
      },
      {
        name: "ElevenLabs",
        description: "Ultra-realistic AI voices and cloning.",
        site: "https://elevenlabs.io/",
        positives: [r("G2", "Most natural TTS I've heard.", "https://www.g2.com/products/elevenlabs/reviews"), r("Product Hunt", "Voice cloning is scary good.", "https://www.producthunt.com/products/elevenlabs")],
        negatives: [r("Reddit", "Character limits burn fast.", "https://www.reddit.com/r/ElevenLabs/"), r("G2", "Some accents still sound off.", "https://www.g2.com/products/elevenlabs/reviews")],
      },
      {
        name: "Runway Gen-3",
        description: "AI video generation and editing suite.",
        site: "https://runwayml.com/",
        positives: [r("Product Hunt", "Gen-3 video quality is incredible.", "https://www.producthunt.com/products/runway"), r("G2", "Great for creative prototypes.", "https://www.g2.com/products/runway/reviews")],
        negatives: [r("Reddit", "Credits run out fast.", "https://www.reddit.com/r/RunwayML/"), r("G2", "Long render queues at peak.", "https://www.g2.com/products/runway/reviews")],
      },
      {
        name: "Stable Diffusion XL",
        description: "Open image model with huge ecosystem.",
        site: "https://stability.ai/",
        positives: [r("Reddit", "Best open-source image model.", "https://www.reddit.com/r/StableDiffusion/"), r("GitHub", "Massive community + models.", "https://github.com/Stability-AI/generative-models")],
        negatives: [r("Reddit", "Needs decent GPU locally.", "https://www.reddit.com/r/StableDiffusion/"), r("Trustpilot", "License changes cause confusion.", "https://www.trustpilot.com/review/stability.ai")],
      },
      {
        name: "Suno AI",
        description: "AI song generation from a text prompt.",
        site: "https://suno.com/",
        positives: [r("Product Hunt", "Full songs from a lyric prompt.", "https://www.producthunt.com/products/suno"), r("Reddit", "V4 vocals are shockingly good.", "https://www.reddit.com/r/SunoAI/")],
        negatives: [r("Reddit", "Copyright concerns still murky.", "https://www.reddit.com/r/SunoAI/"), r("Trustpilot", "Credits burn fast on retries.", "https://www.trustpilot.com/review/suno.com")],
      },
      {
        name: "Luma Dream Machine",
        description: "Text/image to video with cinematic motion.",
        site: "https://lumalabs.ai/dream-machine",
        positives: [r("Product Hunt", "Best cinematic motion generator.", "https://www.producthunt.com/products/luma-dream-machine"), r("Twitter", "Prompt fidelity is impressive.", "https://twitter.com/search?q=dream+machine+luma")],
        negatives: [r("Reddit", "Queue times can be long.", "https://www.reddit.com/r/aivideo/"), r("Product Hunt", "Consistency across shots is hard.", "https://www.producthunt.com/products/luma-dream-machine")],
      },
      {
        name: "HeyGen",
        description: "AI avatars, dubbing, and video creation.",
        site: "https://www.heygen.com/",
        positives: [r("G2", "Best avatar quality on the market.", "https://www.g2.com/products/heygen/reviews"), r("Product Hunt", "Dubbing keeps lip sync tight.", "https://www.producthunt.com/products/heygen")],
        negatives: [r("Reddit", "Pricing tiers confusing.", "https://www.reddit.com/r/videography/"), r("G2", "Editing UI still maturing.", "https://www.g2.com/products/heygen/reviews")],
      },
      {
        name: "Magnific AI",
        description: "AI image upscaler + enhancer.",
        site: "https://magnific.ai/",
        positives: [r("Product Hunt", "Best upscaler for AI images.", "https://www.producthunt.com/products/magnific"), r("Twitter", "Adds detail like nothing else.", "https://twitter.com/search?q=magnific.ai")],
        negatives: [r("Reddit", "Can hallucinate detail.", "https://www.reddit.com/r/StableDiffusion/"), r("Product Hunt", "Credits are pricey.", "https://www.producthunt.com/products/magnific")],
      },
      {
        name: "Adobe Firefly",
        description: "Commercially safe generative imagery.",
        site: "https://firefly.adobe.com/",
        positives: [r("G2", "Baked into Photoshop workflows.", "https://www.g2.com/products/adobe-firefly/reviews"), r("Product Hunt", "IP-safe for enterprise use.", "https://www.producthunt.com/products/adobe-firefly")],
        negatives: [r("Reddit", "Quality trails MJ/SDXL.", "https://www.reddit.com/r/photoshop/"), r("G2", "Credit system opaque.", "https://www.g2.com/products/adobe-firefly/reviews")],
      },
      {
        name: "Udio AI",
        description: "AI music generation with realistic vocals.",
        site: "https://www.udio.com/",
        positives: [r("Product Hunt", "Studio-grade AI music tool.", "https://www.producthunt.com/products/udio"), r("Reddit", "Rivals Suno on vocals.", "https://www.reddit.com/r/udiomusic/")],
        negatives: [r("Reddit", "Editing granularity limited.", "https://www.reddit.com/r/udiomusic/"), r("Trustpilot", "Credit limits on free tier.", "https://www.trustpilot.com/review/udio.com")],
      },
    ],
  },
  {
    key: "cyber",
    label: "Cyber Defense & Security Analytics",
    emoji: "🛡️",
    blurb: "AI for security teams and defenders.",
    glow: "rgba(239, 68, 68, 0.65)",
    tools: [
      {
        name: "Microsoft Security Copilot",
        description: "AI assistant across Microsoft security stack.",
        site: "https://www.microsoft.com/en-us/security/business/ai-machine-learning/microsoft-security-copilot",
        positives: [r("G2", "Speeds up incident triage.", "https://www.g2.com/products/microsoft-security-copilot/reviews"), r("Gartner Peer Insights", "Great Defender/Sentinel integration.", "https://www.gartner.com/reviews/market/security-solutions")],
        negatives: [r("Gartner Peer Insights", "Requires full MS security stack.", "https://www.gartner.com/reviews/market/security-solutions"), r("G2", "Pricing model is complex.", "https://www.g2.com/products/microsoft-security-copilot/reviews")],
      },
      {
        name: "Darktrace DETECT",
        description: "Self-learning AI for network threat detection.",
        site: "https://darktrace.com/",
        positives: [r("Gartner Peer Insights", "Catches anomalies SIEMs miss.", "https://www.gartner.com/reviews/market/network-detection-and-response"), r("G2", "Autonomous response saves hours.", "https://www.g2.com/products/darktrace/reviews")],
        negatives: [r("G2", "Lots of alerts to tune early.", "https://www.g2.com/products/darktrace/reviews"), r("Gartner Peer Insights", "Opaque enterprise pricing.", "https://www.gartner.com/reviews/market/network-detection-and-response")],
      },
      {
        name: "CrowdStrike Charlotte AI",
        description: "AI analyst inside CrowdStrike Falcon.",
        site: "https://www.crowdstrike.com/platform/charlotte-ai/",
        positives: [r("Gartner Peer Insights", "Cuts triage time dramatically.", "https://www.gartner.com/reviews/market/endpoint-protection-platforms"), r("G2", "Natural language threat hunts.", "https://www.g2.com/products/crowdstrike-falcon/reviews")],
        negatives: [r("Gartner Peer Insights", "Requires Falcon platform.", "https://www.gartner.com/reviews/market/endpoint-protection-platforms"), r("G2", "Add-on cost on top of core.", "https://www.g2.com/products/crowdstrike-falcon/reviews")],
      },
      {
        name: "Splunk AI Assistant",
        description: "Natural-language SPL helper in Splunk.",
        site: "https://www.splunk.com/en_us/products/splunk-ai.html",
        positives: [r("G2", "SPL generation from plain English.", "https://www.g2.com/products/splunk-enterprise/reviews"), r("Gartner Peer Insights", "Speeds up junior analysts.", "https://www.gartner.com/reviews/market/security-information-event-management")],
        negatives: [r("Gartner Peer Insights", "Best only inside Splunk Cloud.", "https://www.gartner.com/reviews/market/security-information-event-management"), r("G2", "Cost is a Splunk cost.", "https://www.g2.com/products/splunk-enterprise/reviews")],
      },
      {
        name: "Snyk Code AI",
        description: "AI-powered SAST for developers.",
        site: "https://snyk.io/product/snyk-code/",
        positives: [r("G2", "Best DevSecOps IDE experience.", "https://www.g2.com/products/snyk/reviews"), r("Product Hunt", "AI fix suggestions are great.", "https://www.producthunt.com/products/snyk")],
        negatives: [r("G2", "Free tier limits on private repos.", "https://www.g2.com/products/snyk/reviews"), r("Reddit", "False positives on legacy code.", "https://www.reddit.com/r/devops/")],
      },
      {
        name: "Tines",
        description: "No-code SOAR with AI actions.",
        site: "https://www.tines.com/",
        positives: [r("G2", "Best no-code SOAR I've used.", "https://www.g2.com/products/tines/reviews"), r("Gartner Peer Insights", "Reliable workflow engine.", "https://www.gartner.com/reviews/market/security-orchestration-automation-and-response-solutions")],
        negatives: [r("G2", "AI features still expanding.", "https://www.g2.com/products/tines/reviews"), r("Gartner Peer Insights", "Enterprise-only pricing.", "https://www.gartner.com/reviews/market/security-orchestration-automation-and-response-solutions")],
      },
      {
        name: "Exabeam Insights",
        description: "AI-driven behavioral analytics for SIEM.",
        site: "https://www.exabeam.com/",
        positives: [r("Gartner Peer Insights", "Strong UEBA capabilities.", "https://www.gartner.com/reviews/market/security-information-event-management"), r("G2", "Timeline view is fantastic.", "https://www.g2.com/products/exabeam/reviews")],
        negatives: [r("G2", "Deployment is heavy.", "https://www.g2.com/products/exabeam/reviews"), r("Gartner Peer Insights", "Tuning takes months.", "https://www.gartner.com/reviews/market/security-information-event-management")],
      },
      {
        name: "Vectra AI",
        description: "AI-driven NDR for hybrid cloud.",
        site: "https://www.vectra.ai/",
        positives: [r("Gartner Peer Insights", "Great cloud-native NDR.", "https://www.gartner.com/reviews/market/network-detection-and-response"), r("G2", "Prioritized attack signals.", "https://www.g2.com/products/vectra/reviews")],
        negatives: [r("G2", "UI could be more modern.", "https://www.g2.com/products/vectra/reviews"), r("Gartner Peer Insights", "Pricing on the high side.", "https://www.gartner.com/reviews/market/network-detection-and-response")],
      },
      {
        name: "Greynoise",
        description: "Contextual internet noise + threat intel.",
        site: "https://www.greynoise.io/",
        positives: [r("G2", "Best benign vs. malicious triage.", "https://www.g2.com/products/greynoise/reviews"), r("Reddit", "Massive alert-fatigue reducer.", "https://www.reddit.com/r/cybersecurity/")],
        negatives: [r("Reddit", "Free tier query limits.", "https://www.reddit.com/r/cybersecurity/"), r("G2", "Enterprise API is the good stuff.", "https://www.g2.com/products/greynoise/reviews")],
      },
      {
        name: "SentinelOne Purple AI",
        description: "AI SOC analyst in Singularity platform.",
        site: "https://www.sentinelone.com/platform/purple-ai/",
        positives: [r("Gartner Peer Insights", "Natural-language investigations.", "https://www.gartner.com/reviews/market/endpoint-protection-platforms"), r("G2", "Great hunt query synthesis.", "https://www.g2.com/products/sentinelone/reviews")],
        negatives: [r("G2", "Only with Singularity platform.", "https://www.g2.com/products/sentinelone/reviews"), r("Gartner Peer Insights", "Pricing not transparent.", "https://www.gartner.com/reviews/market/endpoint-protection-platforms")],
      },
    ],
  },
  {
    key: "data",
    label: "Data Analysis & Business Intelligence",
    emoji: "📊",
    blurb: "AI for analysts, PMs, and data teams.",
    glow: "rgba(20, 184, 166, 0.65)",
    tools: [
      {
        name: "Tableau Pulse",
        description: "AI insights layer for Tableau dashboards.",
        site: "https://www.tableau.com/products/tableau-pulse",
        positives: [r("G2", "Auto-summaries speed decisions.", "https://www.g2.com/products/tableau/reviews"), r("Gartner Peer Insights", "Great for exec dashboards.", "https://www.gartner.com/reviews/market/analytics-business-intelligence-platforms")],
        negatives: [r("Gartner Peer Insights", "Requires Tableau Cloud.", "https://www.gartner.com/reviews/market/analytics-business-intelligence-platforms"), r("G2", "Setup on top of existing dashboards.", "https://www.g2.com/products/tableau/reviews")],
      },
      {
        name: "Julius AI",
        description: "AI data analyst — chat with your CSVs.",
        site: "https://julius.ai/",
        positives: [r("Product Hunt", "Beautiful charts from a chat.", "https://www.producthunt.com/products/julius-ai"), r("Twitter", "Fastest way to explore CSVs.", "https://twitter.com/search?q=julius.ai")],
        negatives: [r("Reddit", "Struggles on huge datasets.", "https://www.reddit.com/r/datascience/"), r("Product Hunt", "Credits cap heavy usage.", "https://www.producthunt.com/products/julius-ai")],
      },
      {
        name: "Akkio",
        description: "No-code AI predictions for business teams.",
        site: "https://www.akkio.com/",
        positives: [r("G2", "Non-technical AI in minutes.", "https://www.g2.com/products/akkio/reviews"), r("Product Hunt", "Great for churn/lead scoring.", "https://www.producthunt.com/products/akkio")],
        negatives: [r("G2", "Limited deep customization.", "https://www.g2.com/products/akkio/reviews"), r("Product Hunt", "Best on structured data only.", "https://www.producthunt.com/products/akkio")],
      },
      {
        name: "Polymer",
        description: "AI BI that turns spreadsheets into dashboards.",
        site: "https://www.polymersearch.com/",
        positives: [r("G2", "From CSV to dashboard in minutes.", "https://www.g2.com/products/polymer/reviews"), r("Product Hunt", "AI narrative summaries are neat.", "https://www.producthunt.com/products/polymer")],
        negatives: [r("Reddit", "Not a replacement for real BI.", "https://www.reddit.com/r/BusinessIntelligence/"), r("G2", "Pricing for marketing SKUs high.", "https://www.g2.com/products/polymer/reviews")],
      },
      {
        name: "Rows AI",
        description: "AI-powered spreadsheet with data integrations.",
        site: "https://rows.com/",
        positives: [r("Product Hunt", "The AI spreadsheet done right.", "https://www.producthunt.com/products/rows"), r("G2", "Built-in integrations are killer.", "https://www.g2.com/products/rows/reviews")],
        negatives: [r("Reddit", "Not a full Excel replacement.", "https://www.reddit.com/r/excel/"), r("G2", "AI usage capped by plan.", "https://www.g2.com/products/rows/reviews")],
      },
      {
        name: "MonkeyLearn",
        description: "No-code text analysis with AI.",
        site: "https://monkeylearn.com/",
        positives: [r("G2", "Best no-code NLP for support ops.", "https://www.g2.com/products/monkeylearn/reviews"), r("Product Hunt", "Great pre-built classifiers.", "https://www.producthunt.com/products/monkeylearn")],
        negatives: [r("Reddit", "Product roadmap unclear post-acquisition.", "https://www.reddit.com/r/MachineLearning/"), r("G2", "Enterprise-only for higher volumes.", "https://www.g2.com/products/monkeylearn/reviews")],
      },
      {
        name: "ChatPRD",
        description: "AI copilot for product managers.",
        site: "https://www.chatprd.ai/",
        positives: [r("Product Hunt", "Best PRD drafting workflow.", "https://www.producthunt.com/products/chatprd"), r("Twitter", "Cuts PM writing by half.", "https://twitter.com/search?q=chatprd")],
        negatives: [r("Reddit", "Best with heavy editing.", "https://www.reddit.com/r/ProductManagement/"), r("Product Hunt", "Team features still early.", "https://www.producthunt.com/products/chatprd")],
      },
      {
        name: "Domo AI",
        description: "AI overlays on Domo BI platform.",
        site: "https://www.domo.com/ai",
        positives: [r("Gartner Peer Insights", "Fast dashboard chat answers.", "https://www.gartner.com/reviews/market/analytics-business-intelligence-platforms"), r("G2", "Solid enterprise data platform.", "https://www.g2.com/products/domo/reviews")],
        negatives: [r("G2", "Legacy interface areas remain.", "https://www.g2.com/products/domo/reviews"), r("Gartner Peer Insights", "Priced for large orgs.", "https://www.gartner.com/reviews/market/analytics-business-intelligence-platforms")],
      },
      {
        name: "PowerBI Copilot",
        description: "Microsoft Copilot inside Power BI.",
        site: "https://learn.microsoft.com/en-us/power-bi/create-reports/copilot-introduction",
        positives: [r("G2", "Great DAX + narrative generation.", "https://www.g2.com/products/microsoft-power-bi/reviews"), r("Gartner Peer Insights", "Tight Microsoft 365 fit.", "https://www.gartner.com/reviews/market/analytics-business-intelligence-platforms")],
        negatives: [r("Reddit", "Requires premium capacity.", "https://www.reddit.com/r/PowerBI/"), r("G2", "Feature parity vs. desktop lags.", "https://www.g2.com/products/microsoft-power-bi/reviews")],
      },
      {
        name: "Veezoo",
        description: "Natural-language BI for business users.",
        site: "https://www.veezoo.com/",
        positives: [r("Product Hunt", "Ask data anything, get charts.", "https://www.producthunt.com/products/veezoo"), r("G2", "Great semantic layer approach.", "https://www.g2.com/products/veezoo/reviews")],
        negatives: [r("Reddit", "Best on curated data models.", "https://www.reddit.com/r/BusinessIntelligence/"), r("G2", "Smaller ecosystem than Tableau.", "https://www.g2.com/products/veezoo/reviews")],
      },
    ],
  },
  {
    key: "design",
    label: "UI/UX & Digital Design",
    emoji: "🎨",
    blurb: "AI for designers and visual creators.",
    glow: "rgba(236, 72, 153, 0.65)",
    tools: [
      {
        name: "Galileo AI",
        description: "Text-to-UI for high-fidelity mockups.",
        site: "https://www.usegalileo.ai/",
        positives: [r("Product Hunt", "Best text-to-UI I've seen.", "https://www.producthunt.com/products/galileo-ai"), r("Twitter", "Cuts wireframe time massively.", "https://twitter.com/search?q=galileo.ai")],
        negatives: [r("Reddit", "Outputs need cleanup for prod.", "https://www.reddit.com/r/UXDesign/"), r("Product Hunt", "Waitlist gated early.", "https://www.producthunt.com/products/galileo-ai")],
      },
      {
        name: "v0 by Vercel",
        description: "AI React + Tailwind UI generator.",
        site: "https://v0.dev/",
        positives: [r("Product Hunt", "Ship React UI from a prompt.", "https://www.producthunt.com/products/v0-by-vercel"), r("Twitter", "Shadcn + Tailwind out of the box.", "https://twitter.com/search?q=v0.dev")],
        negatives: [r("Reddit", "Best for Next.js stacks.", "https://www.reddit.com/r/nextjs/"), r("Product Hunt", "Credits burn quickly.", "https://www.producthunt.com/products/v0-by-vercel")],
      },
      {
        name: "Relume",
        description: "AI wireframes + Webflow-ready components.",
        site: "https://www.relume.io/",
        positives: [r("Product Hunt", "AI sitemap + wireframe in minutes.", "https://www.producthunt.com/products/relume"), r("G2", "Massive Webflow component library.", "https://www.g2.com/products/relume/reviews")],
        negatives: [r("Reddit", "Best inside Webflow stack.", "https://www.reddit.com/r/webflow/"), r("G2", "Team seats add up.", "https://www.g2.com/products/relume/reviews")],
      },
      {
        name: "Uizard",
        description: "AI wireframes and app design.",
        site: "https://uizard.io/",
        positives: [r("G2", "Screenshots-to-mockups is fun.", "https://www.g2.com/products/uizard/reviews"), r("Product Hunt", "Great for non-designers.", "https://www.producthunt.com/products/uizard")],
        negatives: [r("Reddit", "Fidelity trails Figma.", "https://www.reddit.com/r/UI_Design/"), r("G2", "Advanced features paywalled.", "https://www.g2.com/products/uizard/reviews")],
      },
      {
        name: "Figma AI",
        description: "AI features baked into Figma.",
        site: "https://www.figma.com/ai/",
        positives: [r("Product Hunt", "Rename layers in one click.", "https://www.producthunt.com/products/figma"), r("Twitter", "First Draft is a real timesaver.", "https://twitter.com/search?q=figma+ai")],
        negatives: [r("Reddit", "Beta features gated.", "https://www.reddit.com/r/FigmaDesign/"), r("G2", "Region availability varies.", "https://www.g2.com/products/figma/reviews")],
      },
      {
        name: "Khroma",
        description: "AI color palette generator personalized for you.",
        site: "https://www.khroma.co/",
        positives: [r("Product Hunt", "My favorite palette explorer.", "https://www.producthunt.com/products/khroma"), r("Twitter", "Learns from your taste.", "https://twitter.com/search?q=khroma.co")],
        negatives: [r("Reddit", "No native app export.", "https://www.reddit.com/r/design_critiques/"), r("Product Hunt", "UI can feel slow.", "https://www.producthunt.com/products/khroma")],
      },
      {
        name: "Looka",
        description: "AI logo maker and brand kit generator.",
        site: "https://looka.com/",
        positives: [r("Trustpilot", "Great starter branding fast.", "https://www.trustpilot.com/review/looka.com"), r("G2", "Good for small biz kits.", "https://www.g2.com/products/looka/reviews")],
        negatives: [r("Trustpilot", "Upsells throughout the flow.", "https://www.trustpilot.com/review/looka.com"), r("G2", "Files behind paywall.", "https://www.g2.com/products/looka/reviews")],
      },
      {
        name: "Fronty",
        description: "Convert images to HTML/CSS via AI.",
        site: "https://fronty.com/",
        positives: [r("Product Hunt", "Fastest way from mockup to HTML.", "https://www.producthunt.com/products/fronty"), r("G2", "Great starting point for prototypes.", "https://www.g2.com/products/fronty/reviews")],
        negatives: [r("Reddit", "Output isn't production-clean.", "https://www.reddit.com/r/webdev/"), r("G2", "Pricing per conversion.", "https://www.g2.com/products/fronty/reviews")],
      },
      {
        name: "Topaz Photo AI",
        description: "AI photo upscaling and sharpening.",
        site: "https://www.topazlabs.com/topaz-photo-ai",
        positives: [r("G2", "Best noise reduction in the game.", "https://www.g2.com/products/topaz-labs/reviews"), r("Reddit", "Saved unusable low-light shots.", "https://www.reddit.com/r/photography/")],
        negatives: [r("Reddit", "Heavy on GPU/CPU.", "https://www.reddit.com/r/photography/"), r("G2", "Upgrade fees each cycle.", "https://www.g2.com/products/topaz-labs/reviews")],
      },
      {
        name: "Photoroom",
        description: "AI background removal + product photo studio.",
        site: "https://www.photoroom.com/",
        positives: [r("App Store", "Best BG remover on mobile.", "https://apps.apple.com/app/photoroom-photo-editor/id1455009060"), r("G2", "Great for ecommerce catalogs.", "https://www.g2.com/products/photoroom/reviews")],
        negatives: [r("Trustpilot", "Pro pricing feels steep.", "https://www.trustpilot.com/review/photoroom.com"), r("Reddit", "Batch limits on free.", "https://www.reddit.com/r/Etsy/")],
      },
    ],
  },
  {
    key: "marketing",
    label: "Social Media & SEO Optimization",
    emoji: "📣",
    blurb: "AI for growth, social, and SEO teams.",
    glow: "rgba(249, 115, 22, 0.7)",
    tools: [
      {
        name: "Surfer SEO",
        description: "AI-driven SEO content optimization.",
        site: "https://surferseo.com/",
        positives: [r("G2", "Best on-page SEO scoring.", "https://www.g2.com/products/surfer/reviews"), r("Trustpilot", "Content Editor is superb.", "https://www.trustpilot.com/review/surferseo.com")],
        negatives: [r("G2", "Costs stack up with team seats.", "https://www.g2.com/products/surfer/reviews"), r("Trustpilot", "Scoring can push over-optimization.", "https://www.trustpilot.com/review/surferseo.com")],
      },
      {
        name: "Albert AI",
        description: "Autonomous digital marketing AI.",
        site: "https://albert.ai/",
        positives: [r("G2", "Runs paid channels autonomously.", "https://www.g2.com/products/albert-ai/reviews"), r("Gartner Peer Insights", "Great for large ad budgets.", "https://www.gartner.com/reviews/market/multichannel-marketing-hubs")],
        negatives: [r("G2", "Enterprise pricing only.", "https://www.g2.com/products/albert-ai/reviews"), r("Gartner Peer Insights", "Needs meaningful ad spend.", "https://www.gartner.com/reviews/market/multichannel-marketing-hubs")],
      },
      {
        name: "Pencil",
        description: "AI-generated ad creative for performance teams.",
        site: "https://www.trypencil.com/",
        positives: [r("Product Hunt", "Ad variants in seconds.", "https://www.producthunt.com/products/pencil"), r("G2", "Nice performance predictions.", "https://www.g2.com/products/pencil/reviews")],
        negatives: [r("Reddit", "Best with strong brand assets.", "https://www.reddit.com/r/PPC/"), r("G2", "Higher tiers get pricey.", "https://www.g2.com/products/pencil/reviews")],
      },
      {
        name: "Munch",
        description: "AI turns long videos into social clips.",
        site: "https://www.getmunch.com/",
        positives: [r("Product Hunt", "Great auto-clipper for creators.", "https://www.producthunt.com/products/munch"), r("Twitter", "Trend-based cuts save hours.", "https://twitter.com/search?q=getmunch")],
        negatives: [r("Reddit", "Sometimes miscaptions clips.", "https://www.reddit.com/r/NewTubers/"), r("Product Hunt", "Renders take time on long uploads.", "https://www.producthunt.com/products/munch")],
      },
      {
        name: "Brand24",
        description: "AI-powered social listening + sentiment.",
        site: "https://brand24.com/",
        positives: [r("G2", "Solid mentions coverage.", "https://www.g2.com/products/brand24/reviews"), r("Trustpilot", "Great sentiment breakdowns.", "https://www.trustpilot.com/review/brand24.com")],
        negatives: [r("G2", "Historical data limited by tier.", "https://www.g2.com/products/brand24/reviews"), r("Trustpilot", "Pricing recently rose.", "https://www.trustpilot.com/review/brand24.com")],
      },
      {
        name: "Opus Clip",
        description: "AI shorts generator from long-form videos.",
        site: "https://www.opus.pro/",
        positives: [r("Product Hunt", "Best AI shorts tool right now.", "https://www.producthunt.com/products/opus-clip"), r("Twitter", "Auto-captions look great.", "https://twitter.com/search?q=opus.pro")],
        negatives: [r("Reddit", "Virality scores are optimistic.", "https://www.reddit.com/r/NewTubers/"), r("Product Hunt", "Credits burn on long uploads.", "https://www.producthunt.com/products/opus-clip")],
      },
      {
        name: "Predis.ai",
        description: "AI social media content + scheduling.",
        site: "https://predis.ai/",
        positives: [r("G2", "Great carousel + video generator.", "https://www.g2.com/products/predis-ai/reviews"), r("Product Hunt", "Solid content-calendar AI.", "https://www.producthunt.com/products/predis-ai")],
        negatives: [r("G2", "Templates can feel repetitive.", "https://www.g2.com/products/predis-ai/reviews"), r("Trustpilot", "Support can be slow.", "https://www.trustpilot.com/review/predis.ai")],
      },
      {
        name: "Ocoya",
        description: "AI content + scheduling for social.",
        site: "https://www.ocoya.com/",
        positives: [r("G2", "All-in-one social suite.", "https://www.g2.com/products/ocoya/reviews"), r("Product Hunt", "Handy AI captions.", "https://www.producthunt.com/products/ocoya")],
        negatives: [r("G2", "Analytics on the light side.", "https://www.g2.com/products/ocoya/reviews"), r("Trustpilot", "Occasional posting hiccups.", "https://www.trustpilot.com/review/ocoya.com")],
      },
      {
        name: "Flick AI",
        description: "AI social copilot for creators.",
        site: "https://www.flick.social/",
        positives: [r("Product Hunt", "Best AI caption assistant.", "https://www.producthunt.com/products/flick"), r("G2", "Great hashtag research.", "https://www.g2.com/products/flick/reviews")],
        negatives: [r("Reddit", "Best for solo creators.", "https://www.reddit.com/r/socialmedia/"), r("G2", "Higher tiers unlock the good stuff.", "https://www.g2.com/products/flick/reviews")],
      },
      {
        name: "Smartly.io",
        description: "Enterprise creative automation for ads.",
        site: "https://www.smartly.io/",
        positives: [r("G2", "Automates thousands of ad variants.", "https://www.g2.com/products/smartly-io/reviews"), r("Gartner Peer Insights", "Great cross-channel scale.", "https://www.gartner.com/reviews/market/multichannel-marketing-hubs")],
        negatives: [r("G2", "Enterprise pricing only.", "https://www.g2.com/products/smartly-io/reviews"), r("Gartner Peer Insights", "Onboarding is heavy.", "https://www.gartner.com/reviews/market/multichannel-marketing-hubs")],
      },
    ],
  },
  {
    key: "automation",
    label: "Workflow & Agentic Orchestration",
    emoji: "⚙️",
    blurb: "AI agents, workflows, and orchestration.",
    glow: "rgba(139, 92, 246, 0.65)",
    tools: [
      {
        name: "Make.com AI",
        description: "Visual automation platform with AI modules.",
        site: "https://www.make.com/",
        positives: [r("G2", "Most flexible visual automation.", "https://www.g2.com/products/make/reviews"), r("Product Hunt", "AI modules snap right in.", "https://www.producthunt.com/products/make")],
        negatives: [r("G2", "Steeper curve than Zapier.", "https://www.g2.com/products/make/reviews"), r("Trustpilot", "Op-based pricing surprises.", "https://www.trustpilot.com/review/make.com")],
      },
      {
        name: "Zapier Central",
        description: "AI agent workspace across your Zaps.",
        site: "https://zapier.com/central",
        positives: [r("Product Hunt", "Bots that live in your stack.", "https://www.producthunt.com/products/zapier"), r("G2", "Tight fit with existing Zaps.", "https://www.g2.com/products/zapier/reviews")],
        negatives: [r("Reddit", "Still early vs. custom agents.", "https://www.reddit.com/r/zapier/"), r("G2", "Task usage adds up.", "https://www.g2.com/products/zapier/reviews")],
      },
      {
        name: "CrewAI",
        description: "Framework for role-based AI agent teams.",
        site: "https://www.crewai.com/",
        positives: [r("GitHub", "Best multi-agent framework.", "https://github.com/joaomdmoura/crewAI"), r("Product Hunt", "Great abstractions for crews.", "https://www.producthunt.com/products/crewai")],
        negatives: [r("Reddit", "Requires devops to run reliably.", "https://www.reddit.com/r/LangChain/"), r("GitHub", "Docs still catching up.", "https://github.com/joaomdmoura/crewAI/issues")],
      },
      {
        name: "Langflow",
        description: "Visual builder for LangChain flows.",
        site: "https://www.langflow.org/",
        positives: [r("GitHub", "Cleanest way to prototype chains.", "https://github.com/langflow-ai/langflow"), r("Product Hunt", "Great drag-drop UX.", "https://www.producthunt.com/products/langflow")],
        negatives: [r("GitHub", "Breaking changes between versions.", "https://github.com/langflow-ai/langflow/issues"), r("Reddit", "Still maturing for prod.", "https://www.reddit.com/r/LangChain/")],
      },
      {
        name: "AutoGPT",
        description: "Open autonomous AI agent framework.",
        site: "https://agpt.co/",
        positives: [r("GitHub", "Sparked the agents movement.", "https://github.com/Significant-Gravitas/AutoGPT"), r("Reddit", "Fun to experiment with.", "https://www.reddit.com/r/AutoGPT/")],
        negatives: [r("Reddit", "Real tasks still tough.", "https://www.reddit.com/r/AutoGPT/"), r("GitHub", "Token costs get real.", "https://github.com/Significant-Gravitas/AutoGPT/issues")],
      },
      {
        name: "Lindy.ai",
        description: "No-code AI employees for ops teams.",
        site: "https://www.lindy.ai/",
        positives: [r("Product Hunt", "Best no-code AI assistant builder.", "https://www.producthunt.com/products/lindy"), r("Twitter", "Great for meeting + email flows.", "https://twitter.com/search?q=lindy.ai")],
        negatives: [r("Reddit", "Pricing per Lindy adds up.", "https://www.reddit.com/r/nocode/"), r("Product Hunt", "Edge tools still expanding.", "https://www.producthunt.com/products/lindy")],
      },
      {
        name: "Flowise",
        description: "Open-source drag-drop LLM flow builder.",
        site: "https://flowiseai.com/",
        positives: [r("GitHub", "Best OSS Langflow alternative.", "https://github.com/FlowiseAI/Flowise"), r("Reddit", "Self-host friendly.", "https://www.reddit.com/r/LocalLLaMA/")],
        negatives: [r("GitHub", "Occasional breaking changes.", "https://github.com/FlowiseAI/Flowise/issues"), r("Reddit", "UX still improving.", "https://www.reddit.com/r/LocalLLaMA/")],
      },
      {
        name: "Relevance AI",
        description: "Build and deploy AI agents for teams.",
        site: "https://relevanceai.com/",
        positives: [r("Product Hunt", "Best low-code agent platform.", "https://www.producthunt.com/products/relevance-ai"), r("G2", "Great for ops-heavy workflows.", "https://www.g2.com/products/relevance-ai/reviews")],
        negatives: [r("G2", "Advanced agents need pro plan.", "https://www.g2.com/products/relevance-ai/reviews"), r("Reddit", "Docs could be deeper.", "https://www.reddit.com/r/nocode/")],
      },
      {
        name: "Zapier Copilot",
        description: "AI copilot that builds Zaps for you.",
        site: "https://zapier.com/ai",
        positives: [r("G2", "Speeds up Zap creation a lot.", "https://www.g2.com/products/zapier/reviews"), r("Product Hunt", "Great starter for automations.", "https://www.producthunt.com/products/zapier")],
        negatives: [r("Reddit", "Complex Zaps still need manual work.", "https://www.reddit.com/r/zapier/"), r("G2", "Requires paid Zapier plan.", "https://www.g2.com/products/zapier/reviews")],
      },
      {
        name: "n8n LangChain",
        description: "Open workflow automation with LangChain nodes.",
        site: "https://n8n.io/",
        positives: [r("GitHub", "Best self-hostable automation.", "https://github.com/n8n-io/n8n"), r("Reddit", "LangChain nodes are powerful.", "https://www.reddit.com/r/selfhosted/")],
        negatives: [r("Reddit", "Steep for non-devs.", "https://www.reddit.com/r/selfhosted/"), r("GitHub", "License changes caused fuss.", "https://github.com/n8n-io/n8n/issues")],
      },
    ],
  },
];
